/** Istilah bab Turunan dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'laju perubahan rata-rata', arti: 'selisih hasil dibagi selisih waktu (selisih dibagi selisih); sama dengan kemiringan garis penghubung dua titik pada kurva' },
  { istilah: 'garis potong (sekan)', arti: 'garis lurus yang menghubungkan dua titik pada kurva' },
  { istilah: 'garis singgung', arti: 'garis yang dituju garis potong saat titik keduanya mendekati titik pertama; menyentuh kurva dengan kemiringan sama dengan kurva di titik itu' },
  { istilah: 'kemiringan sesaat', arti: 'kemiringan garis singgung di satu titik; angkanya disebut turunan di titik itu' },
  { istilah: 'turunan di satu titik', arti: 'f′(x₁) = lim h→0 (f(x₁ + h) − f(x₁))/h; satu angka untuk satu titik, bukan garis dan bukan rumus' },
  { istilah: 'definisi limit turunan', arti: 'limit dari selisih dibagi selisih saat h mendekati nol; h tidak boleh nol pada pecahan asalnya' },
  { istilah: 'fungsi turunan', arti: 'f′, fungsi baru yang nilainya kemiringan di tiap x; untuk f(x) = x², f′(x) = 2x' },
  { istilah: 'notasi aksen', arti: 'f′(x), cara menulis turunan dengan tanda aksen' },
  { istilah: 'notasi Leibniz', arti: 'dy/dx, laju perubahan y terhadap x; bukan pembagian y dengan x' },
  { istilah: 'aturan pangkat', arti: 'untuk f(x) = a·xⁿ berlaku f′(x) = a·n·xⁿ⁻¹; pangkat dikalikan ke depan, lalu pangkatnya berkurang satu; hasil hitungan limit, bukan hafalan' },
  { istilah: 'turunan konstanta', arti: 'nol, sebab grafik fungsi konstan mendatar' },
  { istilah: 'suku demi suku', arti: 'jumlah dan selisih boleh diturunkan tiap sukunya; angka pengali ikut terbawa' },
  { istilah: 'aturan hasil kali', arti: '(uv)′ = u′v + uv′; turunan hasil kali bukan hasil kali turunan' },
  { istilah: 'aturan hasil bagi', arti: '(u/v)′ = (u′v − uv′)/v²; urutan pembilangnya tidak boleh dibalik' },
  { istilah: 'aturan rantai', arti: 'untuk fungsi bertingkat: turunkan bagian luarnya, lalu kalikan dengan turunan bagian dalamnya; dy/dx = (dy/du) · (du/dx)' },
  { istilah: 'bagian dalam dan bagian luar', arti: 'pada (x² + 1)³, bagian dalam x² + 1 dan bagian luar pangkat tiga' },
  { istilah: 'turunan sinus dan kosinus', arti: 'turunan sin x adalah cos x; turunan cos x adalah −sin x (tanda minusnya jangan hilang); berlaku dalam radian' },
  { istilah: 'turunan tan x', arti: '1/cos² x = sec² x, dari aturan hasil bagi' },
  { istilah: 'bilangan e', arti: 'kira-kira 2,718; satu-satunya bilangan pokok yang membuat kemiringan kurva eˣ sama dengan tingginya: turunan eˣ adalah eˣ' },
  { istilah: 'persamaan garis singgung', arti: 'y − y₁ = m(x − x₁) dengan m = f′(x₁), bukan f(x₁)' },
  { istilah: 'garis normal', arti: 'garis tegak lurus garis singgung di titik singgung yang sama' },
  { istilah: 'naik dan turun', arti: 'fungsi naik di tempat f′(x) > 0, turun di tempat f′(x) < 0; yang dibaca hanya TANDA turunannya' },
  { istilah: 'titik stasioner', arti: 'tempat f′(x) = 0, kurvanya sedang diam mendatar; belum tentu puncak atau lembah' },
  { istilah: 'tabel tanda', arti: 'cari akar f′, tandai pada garis bilangan, uji tanda f′ di tiap selang' },
  { istilah: 'titik balik maksimum', arti: 'tanda f′ berubah dari positif ke negatif' },
  { istilah: 'titik balik minimum', arti: 'tanda f′ berubah dari negatif ke positif' },
  { istilah: 'nilai optimum', arti: 'nilai terbesar atau terkecil fungsi; dicari dari f′(x) = 0, lalu diperiksa tanda dan ujung selangnya; jawabannya nilai fungsinya, bukan x' },
  { istilah: 'turunan kedua', arti: 'turunan dari turunan, f″; dari posisi ke kecepatan lalu ke percepatan' },
  { istilah: 'biaya marginal', arti: 'turunan biaya total: biaya membuat satu barang tambahan' },
]
