/** Istilah bab Transformasi Geometri dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'transformasi', arti: 'aturan yang memasangkan setiap titik dengan satu titik tujuan; gambar ikut pindah karena semua titiknya pindah' },
  { istilah: 'prapeta', arti: 'titik atau bentuk asal sebelum ditransformasi, ditulis P' },
  { istilah: 'peta (bayangan)', arti: 'hasil transformasi, ditulis P′' },
  { istilah: 'pencerminan (refleksi)', arti: 'memindahkan titik ke seberang garis cermin, tegak lurus garisnya, dengan jarak yang sama' },
  { istilah: 'cermin pada sumbu x', arti: '(x, y) menjadi (x, −y)' },
  { istilah: 'cermin pada sumbu y', arti: '(x, y) menjadi (−x, y)' },
  { istilah: 'cermin pada garis x = h', arti: '(x, y) menjadi (2h − x, y); angka 2h datang dari menghitung jarak lalu menambahkannya kembali' },
  { istilah: 'cermin pada garis y = k', arti: '(x, y) menjadi (x, 2k − y)' },
  { istilah: 'cermin pada garis y = x', arti: 'menukar koordinat: (x, y) menjadi (y, x)' },
  { istilah: 'cermin pada garis y = −x', arti: 'menukar tempat lalu membalik kedua tanda: (x, y) menjadi (−y, −x)' },
  { istilah: 'cermin pada titik', arti: 'pencerminan pada titik M(a, b): M tepat di tengah prapeta dan peta, rumusnya (2a − x, 2b − y); sama dengan rotasi 180°' },
  { istilah: 'translasi (geseran)', arti: 'menambahkan vektor geseran ke setiap titik: (x, y) oleh (a, b) menjadi (x + a, y + b); bentuk dan ukuran tetap' },
  { istilah: 'rotasi (perputaran)', arti: 'memutar titik terhadap pusat dengan sudut tertentu; jarak ke pusat tetap, arahnya berubah; positif = berlawanan arah jarum jam' },
  { istilah: 'rumus rotasi', arti: 'terhadap titik asal sejauh sudut a: (x cos a − y sin a, x sin a + y cos a)' },
  { istilah: 'pusat rotasi', arti: 'titik yang diam saat diputar; kalau bukan titik asal, kerjakan tiga langkah: geser, putar, geser kembali' },
  { istilah: 'dilatasi (perkalian)', arti: 'memperbesar atau memperkecil dari sebuah pusat: jarak tiap titik ke pusat menjadi k kali semula' },
  { istilah: 'faktor skala k', arti: 'pengali dilatasi: k > 1 memperbesar, 0 < k < 1 memperkecil, k negatif melempar bentuk ke seberang pusat' },
  { istilah: 'isometri', arti: 'transformasi yang menjaga panjang dan sudut: pencerminan, translasi, rotasi; dilatasi bukan' },
  { istilah: 'arah putar (orientasi)', arti: 'urutan titik searah atau berlawanan jarum jam; hanya pencerminan pada garis yang membaliknya' },
  { istilah: 'luas setelah dilatasi', arti: 'berubah k² kali, bukan k kali' },
  { istilah: 'matriks 2×2', arti: 'empat angka pengali disusun dua baris dua kolom [[a, b], [c, d]]; dikalikan titik (x, y) memberi (ax + by, cx + dy)' },
  { istilah: 'kolom matriks', arti: 'kolom pertama = peta titik (1, 0), kolom kedua = peta titik (0, 1); cara menyusun matriks tanpa menghafal' },
  { istilah: 'matriks transformasi', arti: 'matriks tiap transformasi berpusat di titik asal; translasi TIDAK punya matriks pengali, translasi adalah penjumlahan matriks kolom' },
  { istilah: 'komposisi transformasi', arti: 'mengerjakan transformasi kedua pada HASIL yang pertama; pada T₂ ∘ T₁, T₁ dikerjakan lebih dahulu' },
  { istilah: 'matriks gabungan', arti: 'M₂M₁ untuk T₁ lalu T₂: yang dikerjakan pertama ditulis paling kanan karena paling dekat dengan titiknya' },
  { istilah: 'urutan menentukan', arti: 'membalik urutan komposisi biasanya mengubah hasil; pengecualiannya dua translasi atau dua rotasi sepusat' },
]
