/** Istilah bab Ruang Tiga Dimensi dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'gambar ruang', arti: 'ruang yang dipipihkan ke kertas; selalu ada keterangan yang hilang, jadi yang menentukan kedudukan adalah bendanya, bukan gambarnya' },
  { istilah: 'garis putus-putus', arti: 'rusuk yang terhalang benda di depannya; bukan berarti tidak ada' },
  { istilah: 'berpotongan', arti: 'dua garis yang punya tepat satu titik bersama' },
  { istilah: 'sejajar', arti: 'dua garis pada satu bidang yang tidak pernah bertemu' },
  { istilah: 'bersilangan', arti: 'dua garis yang tidak sejajar dan tidak berpotongan; tidak ada satu bidang pun yang memuat keduanya; hanya mungkin di ruang' },
  { istilah: 'garis menembus bidang', arti: 'garis dan bidang yang punya tepat satu titik bersama' },
  { istilah: 'bidang sejajar', arti: 'dua bidang yang tidak punya titik bersama' },
  { istilah: 'garis potong bidang', arti: 'garis penuh tempat dua bidang bertemu; dua bidang tidak pernah bertemu di satu titik saja' },
  { istilah: 'jarak', arti: 'yang terpendek, dan yang terpendek selalu tegak lurus (alasannya Pythagoras: sisi miring selalu lebih panjang)' },
  { istilah: 'kaki tegak lurus', arti: 'titik tempat ruas tegak lurus mendarat; semua soal jarak di bangun ruang berujung pada mencari titik ini' },
  { istilah: 'diagonal sisi', arti: 'ruas dari sudut ke sudut pada satu sisi kubus; panjangnya a√2 untuk rusuk a' },
  { istilah: 'diagonal ruang', arti: 'ruas dari sudut ke sudut yang menembus isi kubus; panjangnya a√3, hasil Pythagoras dua kali' },
  { istilah: 'jarak titik ke garis', arti: 'panjang ruas tegak lurus dari titik ke garis; jalan pintas d = 2L/a (dua kali luas segitiga dibagi alasnya)' },
  { istilah: 'jarak titik ke bidang', arti: 'panjang ruas tegak lurus dari titik sampai menusuk bidang; jalan pintas d = 3V/L (tiga kali volume limas dibagi luas alas)' },
  { istilah: 'jarak garis ke bidang sejajar', arti: 'ambil satu titik sembarang pada garis, lalu ukur jarak titik itu ke bidang; boleh sembarang karena jaraknya tetap' },
  { istilah: 'jarak dua bidang sejajar', arti: 'ambil satu titik pada bidang pertama, ukur jaraknya ke bidang kedua' },
  { istilah: 'proyeksi', arti: 'bayangan titik atau garis pada bidang, dijatuhkan tegak lurus' },
  { istilah: 'sudut dua garis bersilangan', arti: 'geser salah satu garis sejajar dirinya sendiri sampai bertemu, lalu ukur sudutnya di sana; menggeser tidak mengubah arah' },
  { istilah: 'sudut garis dengan bidang', arti: 'sudut antara garis dan proyeksinya (bayangannya) pada bidang itu' },
  { istilah: 'sudut dua bidang', arti: 'sudut antara dua garis yang masing-masing tegak lurus garis potong kedua bidang, bertumpu di satu titik yang sama' },
  { istilah: 'sudut tidak tumpul', arti: 'jawaban sudut di ruang selalu diambil antara 0° dan 90°' },
  { istilah: 'kubus', arti: 'bangun dengan 12 rusuk sama panjang, 6 sisi persegi, 8 titik sudut; bangun latihan utama bab ini' },
  { istilah: 'limas', arti: 'bangun dengan alas bidang datar dan satu puncak; volumenya sepertiga luas alas kali tinggi' },
]
