"""Penggantian TANGAN penyisiran bahasa 21 Sep 2026 (pasangan sapu_bahasa.py).

Kata ganti "ia" untuk benda diganti nama bendanya, "bukan kebetulan" dan
"bukan hiasan" diganti kalimat lugas, benda yang dihidupkan (bercerita,
menutup perkara, memancing, kembaran, bersaudara) diganti kata biasa, cap
penyemangat kuis diganti kalimat apa adanya, dan menggoda/menipu/menyesatkan
diganti "tampak benar", "terpengaruh", "memberi kesan keliru". Tiap butir:
(berkas relatif web/, teks lama, teks baru); teks lama harus ada, semua
kemunculannya diganti. Dijalankan sekali; disimpan supaya keputusan katanya
terbaca, bukan hilang di riwayat chat.

    python alat/sapu_bahasa_tangan.py --coba     periksa semua teks lama ada
    python alat/sapu_bahasa_tangan.py            lakukan
"""
from __future__ import annotations

import sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1] / "web"

GANTI: list[tuple[str, str, str]] = [
    # ---------------- grafik-fungsi ----------------
    ("content/grafik-fungsi/kuis.ts", "sehingga ia memang fungsi.", "sehingga kurva itu memang fungsi."),
    ("content/grafik-fungsi/kuis.ts", "hanya bila ia satu-satu:", "hanya bila fungsi itu satu-satu:"),
    ("content/grafik-fungsi/tahap.ts", "tapi ia terbawa terus.", "tapi kekeliruan itu terbawa terus."),
    ("content/grafik-fungsi/tahap.ts", "tapi ia yang membedakan siswa", "tapi kalimat itulah yang membedakan siswa"),
    ("content/grafik-fungsi/tahap.ts", "bukan fungsi, ia mesin rusak.", "bukan fungsi, tetapi mesin rusak."),
    ("content/grafik-fungsi/tahap.ts", "jadi ia gagal.", "jadi lingkaran gagal."),
    ("content/grafik-fungsi/tahap.ts", "tetapi ia bukan grafik fungsi.", "tetapi lingkaran bukan grafik fungsi."),
    ("content/grafik-fungsi/tahap.ts", "barulah ia menjadi fungsi.", "barulah potongan itu menjadi fungsi."),
    ("content/grafik-fungsi/tahap.ts", "Kapan ia nol? Hanya saat x = h.", "Kapan isi kurungnya nol? Hanya saat x = h."),
    ("content/grafik-fungsi/tahap.ts", "Kalau kurungnya x + 3, ia nol saat x bernilai -3", "Kalau kurungnya x + 3, isinya nol saat x bernilai -3"),
    ("content/grafik-fungsi/tahap.ts", "Tapi ia bukan parabola jenis lain. Ia parabola yang sama,", "Tapi itu bukan parabola jenis lain. Parabolanya sama,"),
    ("content/grafik-fungsi/tahap.ts", "tetapi ia tidak cuma memberi jawaban: ia mengembalikan rumusnya", "tetapi cara ini tidak cuma memberi jawaban: cara ini mengembalikan rumusnya"),
    ("content/grafik-fungsi/tahap.ts", "dan begitulah biasanya ia diajarkan.", "dan begitulah biasanya daftar itu diajarkan."),
    ("content/grafik-fungsi/tahap.ts", "Di sini ia dipakai untuk satu keperluan saja:", "Di sini kurva sinus dipakai untuk satu keperluan saja:"),
    ("content/grafik-fungsi/tahap.ts", "jadi ia mengerjakan HASILNYA.", "jadi mutlaknya mengerjakan HASILNYA."),
    ("content/grafik-fungsi/tahap.ts", "jadi ia mengerjakan MASUKANNYA.", "jadi mutlaknya mengerjakan MASUKANNYA."),
    ("content/grafik-fungsi/tahap.ts", "pada awalnya ia memang terlihat biasa saja.", "pada awalnya pertumbuhannya memang terlihat biasa saja."),
    ("content/grafik-fungsi/tahap.ts", "Ia turun terus, makin lama makin mendatar, dan makin dekat ke sumbu x. Tetapi ia tidak pernah menyentuhnya.", "Grafiknya turun terus, makin lama makin mendatar, dan makin dekat ke sumbu x. Tetapi grafiknya tidak pernah menyentuh sumbu itu."),
    ("content/grafik-fungsi/tahap.ts", "Ia grafik eksponen yang dilipat pada garis y = x.", "Grafik logaritma adalah grafik eksponen yang dilipat pada garis y = x."),
    ("content/grafik-fungsi/tahap.ts", "Menjadi apa ia setelah dilipat?", "Menjadi apa grafiknya setelah dilipat?"),
    ("content/grafik-fungsi/tahap.ts", "Ia terbelah menjadi dua bagian yang tidak bersambung", "Grafiknya terbelah menjadi dua bagian yang tidak bersambung"),
    ("content/grafik-fungsi/tahap.ts", "tetapi ia masih bilangan positif.", "tetapi angka itu masih bilangan positif."),
    ("content/grafik-fungsi/tahap.ts", "Di x = 1.000.000.000 pun ia masih positif.", "Di x = 1.000.000.000 pun nilainya masih positif."),
    ("content/grafik-fungsi/tahap.ts", "Mesin itu ada, dan ia yang menutup seluruh isi topik ini.", "Mesin itu ada, dan mesin itulah penutup seluruh isi topik ini."),
    ("content/grafik-fungsi/tahap.ts", "Ia membatalkan pekerjaan fungsi aslinya,", "Invers membatalkan pekerjaan fungsi aslinya,"),
    ("content/grafik-fungsi/tahap.ts", "saat ia muncul di luar buku pelajaran.", "saat bentuk itu muncul di luar buku pelajaran."),
    ("content/grafik-fungsi/tahap.ts", "Ia terbaca langsung dari bentuk grafiknya,", "Kesimpulan itu terbaca langsung dari bentuk grafiknya,"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya kuat karena kata naik", "Terasa benar karena kata naik"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya masuk akal: di banyak soal,", "Terasa masuk akal: di banyak soal,"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya wajar: akarnya", "Terasa wajar: akarnya"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya kuat karena mengalikan dua", "Terasa benar karena mengalikan dua"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya masuk akal: di hampir semua hitungan lain,", "Terasa masuk akal: di hampir semua hitungan lain,"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya datang dari mata:", "Kesan itu datang dari mata:"),
    ("content/grafik-fungsi/tahap.ts", "Godaannya kuat karena di aljabar biasa", "Terasa benar karena di aljabar biasa"),
    ("content/grafik-fungsi/tahap.ts", "judul: 'Grafik itu bercerita'", "judul: 'Membaca grafik seperti membaca cerita'"),
    ("content/grafik-fungsi/tahap.ts", "gambar yang sama akan bercerita hal yang berbeda.", "gambar yang sama akan menunjukkan hal yang berbeda."),
    # ---------------- integral ----------------
    ("content/integral/kuis.ts", "Hasil 0 itu bukan kebetulan:", "Hasil 0 itu ada sebabnya:"),
    ("content/integral/tahap.ts", "Pembaginya bukan hiasan. Ia ada untuk membatalkan", "Pembaginya penting. Pembagi itu ada untuk membatalkan"),
    ("content/integral/tahap.ts", "Ia turunan dari isi kurungnya.", "Itu turunan dari isi kurungnya."),
    ("content/integral/tahap.ts", "Ia aturan rantai yang dibaca dari kanan ke kiri.", "Substitusi adalah aturan rantai yang dibaca dari kanan ke kiri."),
    ("content/integral/tahap.ts", "Ia hanya bekerja kalau sisa soal,", "Substitusi hanya bekerja kalau sisa soal,"),
    ("content/integral/tahap.ts", "Godaannya kuat karena pada bentuk seperti (x + 1)⁵", "Terasa benar karena pada bentuk seperti (x + 1)⁵"),
    ("content/integral/tahap.ts", "Ia dimuat di sini karena ada di buku", "Parsial dimuat di sini karena ada di buku"),
    ("content/integral/tahap.ts", "Godaannya besar untuk menyimpulkan bahwa itu selalu terjadi.", "Mudah sekali menyimpulkan bahwa itu selalu terjadi."),
    ("content/integral/tahap.ts", "Godaannya kuat karena semua contoh awal", "Terasa benar karena semua contoh awal"),
    ("content/integral/tahap.ts", "jadi ia berubah saat x digeser.", "jadi nilainya berubah saat x digeser."),
    ("content/integral/tahap.ts", "Materi ini menjelaskan kenapa itu bukan kebetulan.", "Materi ini menjelaskan kenapa keduanya memang harus sama."),
    ("content/integral/tahap.ts", "disebut dasar: ia menopang hampir semua hitungan integral", "disebut dasar: teorema ini menopang hampir semua hitungan integral"),
    ("content/integral/tahap.ts", "ia memang ada, cuma tidak pernah bertahan", "C memang ada, cuma tidak pernah bertahan"),
    ("content/integral/tahap.ts", "jarang salah karena konsepnya; ia salah karena langkahnya", "jarang salah karena konsepnya; salahnya karena langkahnya"),
    ("content/integral/tahap.ts", "Tanda kurung siku itu bukan hiasan: ia mengingatkan", "Tanda kurung siku itu ada gunanya: tanda itu mengingatkan"),
    ("content/integral/tahap.ts", "Godaannya kuat karena hasilnya tetap keluar", "Terasa benar karena hasilnya tetap keluar"),
    ("content/integral/tahap.ts", "Kadang ia cuma menyentuh sumbu", "Kadang kurvanya cuma menyentuh sumbu"),
    ("content/integral/tahap.ts", "Ia jawaban yang benar untuk pertanyaan \"berapa hasil integralnya\". Ia hanya salah", "Angka itu jawaban yang benar untuk pertanyaan \"berapa hasil integralnya\". Angka itu hanya salah"),
    ("content/integral/tahap.ts", "Ia memperlihatkan di mana semua ini benar-benar dipakai", "Materi ini memperlihatkan di mana semua ini benar-benar dipakai"),
    ("content/integral/tahap.ts", "godaannya besar untuk menganggap urutannya tidak penting", "mudah sekali menganggap urutannya tidak penting"),
    ("content/integral/tahap.ts", "tetapi menyesatkan begitu daerahnya lebih dari satu", "tetapi salah begitu daerahnya lebih dari satu"),
    ("content/integral/tahap.ts", "Ia memperlihatkan empat keadaan", "Galeri ini memperlihatkan empat keadaan"),
    ("content/integral/tahap.ts", "bagaimana urutan kerja yang tidak tersesat?", "bagaimana urutan kerja yang tidak salah jalan?"),
    # ---------------- limit ----------------
    ("content/limit/istilah.ts", "ia ikut menuju angka itu", "fungsi itu ikut menuju angka itu"),
    ("content/limit/latihan.ts", "jadi ia tidak sama dengan 1 dan tidak sama dengan 0.", "jadi bentuk itu tidak sama dengan 1 dan tidak sama dengan 0."),
    ("content/limit/latihan.ts", "Ia disebut bentuk tak tentu: bentuk itu", "Namanya bentuk tak tentu: bentuk itu"),
    ("content/limit/tahap.ts", "Ia angka biasa: 1, lalu 0,5,", "Semuanya angka biasa: 1, lalu 0,5,"),
    ("content/limit/tahap.ts", "Menuju ke angka berapa ia?", "Menuju ke angka berapa nilainya?"),
    ("content/limit/tahap.ts", "Ia dipakai untuk menghitung laju perubahan apa pun:", "Limit dipakai untuk menghitung laju perubahan apa pun:"),
    ("content/limit/tahap.ts", "Ia hanya melihat tetangga-tetangganya.", "Limit hanya melihat tetangga-tetangganya."),
    ("content/limit/tahap.ts", "Kalau kita hanya memeriksa dari kiri, kita bisa tertipu.", "Kalau kita hanya memeriksa dari kiri, kita bisa salah."),
    ("content/limit/tahap.ts", "Kalau ia benar-benar menuju L,", "Kalau fungsinya benar-benar menuju L,"),
    ("content/limit/tahap.ts", "Di angka berapa ia berhenti?", "Di angka berapa nilainya berhenti?"),
    ("content/limit/tahap.ts", "kecuali di x = 1 tempat ia berlubang.", "kecuali di x = 1 tempat garisnya berlubang."),
    ("content/limit/tahap.ts", "Malah karena tidak peduli, ia masih bisa menjawab", "Malah karena tidak peduli, limit masih bisa menjawab"),
    ("content/limit/tahap.ts", "Ia disebut bentuk tak tentu, artinya", "Bentuk itu disebut bentuk tak tentu, artinya"),
    ("content/limit/tahap.ts", "Jalan pintas itu bukan tebakan. Ia berdiri di atas", "Jalan pintas itu bukan tebakan. Jalan pintas itu berdiri di atas"),
    ("content/limit/tahap.ts", "Ia berarti bentuk yang Anda tulis belum memberi tahu apa-apa.", "Artinya, bentuk yang Anda tulis belum memberi tahu apa-apa."),
    ("content/limit/tahap.ts", "Karena itu ia dibahas tuntas di materi berikutnya.", "Karena itu cara ini dibahas tuntas di materi berikutnya."),
    ("content/limit/tahap.ts", "padahal ia hanya sah kalau (x - 2) bukan nol", "padahal pencoretan itu hanya sah kalau (x - 2) bukan nol"),
    ("content/limit/tahap.ts", "Tak hingga bukan bilangan, jadi ia tidak bisa disubstitusi.", "Tak hingga bukan bilangan, jadi tidak bisa disubstitusi."),
    ("content/limit/tahap.ts", "Ia keterangan arah: x dibuat sebesar-besarnya tanpa batas.", "Tak hingga adalah keterangan arah: x dibuat sebesar-besarnya tanpa batas."),
    ("content/limit/tahap.ts", "Ia tidak bisa dimasukkan ke rumus, karena tidak ada angka", "Tak hingga tidak bisa dimasukkan ke rumus, karena tidak ada angka"),
    ("content/limit/tahap.ts", "ia bahkan tidak pernah menyentuhnya, karena selalu ada sisa", "kurvanya bahkan tidak pernah menyentuh garis itu, karena selalu ada sisa"),
    ("content/limit/tahap.ts", "keterangan arah: ia memberi tahu bahwa x dibuat membesar", "keterangan arah yang memberi tahu bahwa x dibuat membesar"),
    ("content/limit/tahap.ts", "muncul godaan memasukkannya ke rumus", "orang mudah memasukkannya ke rumus"),
    ("content/limit/tahap.ts", "Ia tidak punya pilihan lain selain ikut menuju 1.", "Fungsi yang terjepit itu tidak punya pilihan lain selain ikut menuju 1."),
    ("content/limit/tahap.ts", "dan ia memang bekerja pada banyak soal.", "dan aturan itu memang bekerja pada banyak soal."),
    ("content/limit/tahap.ts", "Ada godaan besar untuk memakainya di sini.", "Rasanya ingin memakainya di sini."),
    ("content/limit/tahap.ts", "Sebagai alat hitung cepat ia sah dipakai di soal lain, tetapi sebagai bukti untuk limit ini ia tidak berlaku.", "Sebagai alat hitung cepat aturan itu sah dipakai di soal lain, tetapi sebagai bukti untuk limit ini aturan itu tidak berlaku."),
    ("content/limit/tahap.ts", "sehingga muncul godaan mencoret x", "sehingga orang mudah mencoret x"),
    ("content/limit/tahap.ts", "Ia menjawab pertanyaan tentang tujuan, bukan tentang keadaan.", "Limit menjawab pertanyaan tentang tujuan, bukan tentang keadaan."),
    # ---------------- ruang-3d ----------------
    ("content/ruang-3d/tahap.ts", "labelPendek: 'Gambar yang menipu'", "labelPendek: 'Gambar yang mengecoh mata'"),
    ("content/ruang-3d/tahap.ts", "Kapan ia berubah dari", "Kapan gambarnya berubah dari"),
    ("content/ruang-3d/tahap.ts", "judul: 'Kenapa gambarnya bisa menipu'", "judul: 'Kenapa gambarnya bisa salah dibaca'"),
    ("content/ruang-3d/tahap.ts", "jadi ia ada tetapi tidak terlihat langsung.", "jadi rusuk itu ada tetapi tidak terlihat langsung."),
    ("content/ruang-3d/tahap.ts", "ia sejajar atau berpotongan. Kalau tidak bisa, ia bersilangan.", "keduanya sejajar atau berpotongan. Kalau tidak bisa, keduanya bersilangan."),
    ("content/ruang-3d/tahap.ts", "Bentuk apa yang ia gambar?", "Bentuk apa yang tergambar?"),
    ("content/ruang-3d/tahap.ts", "judul: 'Pythagoras yang menutup perkara'", "judul: 'Pythagoras menyelesaikan sisanya'"),
    ("content/ruang-3d/tahap.ts", "Godaannya besar: menghubungkan B ke ujung A atau ujung C,", "Yang terasa benar: menghubungkan B ke ujung A atau ujung C,"),
    ("content/ruang-3d/tahap.ts", "Ia menembus bagian dalam kubus. Di sinilah orang sering tersesat,", "Diagonal itu menembus bagian dalam kubus. Di sinilah orang sering salah langkah,"),
    ("content/ruang-3d/tahap.ts", "Apakah ia menempel pada salah satu sisi kubus?", "Apakah garis itu menempel pada salah satu sisi kubus?"),
    ("content/ruang-3d/tahap.ts", "Ia Pythagoras yang dipakai untuk kedua kalinya,", "Rumus itu Pythagoras yang dipakai untuk kedua kalinya,"),
    ("content/ruang-3d/tahap.ts", "Angka 3 di dalam akar itu bukan kebetulan: ia menghitung", "Angka 3 di dalam akar itu ada artinya: angka itu menghitung"),
    ("content/ruang-3d/tahap.ts", "Ia jatuh di suatu tempat di dalam kubus yang tidak punya nama.", "Kakinya jatuh di suatu tempat di dalam kubus yang tidak punya nama."),
    ("content/ruang-3d/tahap.ts", "Apakah ia berada di rusuk mana pun?", "Apakah titik itu berada di rusuk mana pun?"),
    ("content/ruang-3d/tahap.ts", "Pasangan itulah yang dipakai untuk memancing jaraknya keluar.", "Pasangan itulah yang dipakai untuk menghitung jaraknya."),
    ("content/ruang-3d/tahap.ts", "Rumus itu bukan hafalan baru, ia cuma luas segitiga yang dibalik.", "Rumus itu bukan hafalan baru, cuma luas segitiga yang dibalik."),
    ("content/ruang-3d/tahap.ts", "dan ia memotong pojok kubus seperti pisau", "dan bidang itu memotong pojok kubus seperti pisau"),
    ("content/ruang-3d/tahap.ts", "Mengenali kembaran seperti ini menghemat banyak waktu di ujian.", "Mengenali kesamaan seperti ini menghemat banyak waktu di ujian."),
    ("content/ruang-3d/tahap.ts", "godaannya adalah menghitung AB, AD, atau AE", "yang sering terjadi adalah menghitung AB, AD, atau AE"),
    ("content/ruang-3d/tahap.ts", "tetapi ia miring terhadap bidang itu,", "tetapi ruas itu miring terhadap bidang itu,"),
    ("content/ruang-3d/tahap.ts", "apakah ia ikut berputar?", "apakah garis itu ikut berputar?"),
    ("content/ruang-3d/tahap.ts", "Ia dipelajari di bab Trigonometri buku sekolah,", "Aturan kosinus dipelajari di bab Trigonometri buku sekolah,"),
    ("content/ruang-3d/tahap.ts", "Di mana ia berada, dan apa hubungannya dengan AG?", "Di mana ruas itu berada, dan apa hubungannya dengan AG?"),
    # ---------------- statistika ----------------
    ("content/statistika/istilah.ts", "langsung tertipu pencilan", "langsung terpengaruh pencilan"),
    ("content/statistika/kuis.ts", "Pilihan C tertipu oleh kesan gambar", "Pilihan C terbawa kesan gambar"),
    ("content/statistika/kuis.ts", "Pilihan C, semua benar, tertipu pernyataan (3)", "Pilihan C, semua benar, terbawa pernyataan (3)"),
    ("content/statistika/kuis.ts", "ia tidak menyatakan yang satu menyebabkan yang lain.", "korelasi tidak menyatakan yang satu menyebabkan yang lain."),
    ("content/statistika/kuis.ts", "ia tetap menempati posisi terakhir,", "nilai itu tetap menempati posisi terakhir,"),
    ("content/statistika/kuis.ts", "ia tetap memperhitungkan posisi data terbesar", "median tetap memperhitungkan posisi data terbesar"),
    ("content/statistika/kuis.ts", "(Kalau hanya satu 10, ia tidak menjadi modus.)", "(Kalau hanya satu 10, angka itu tidak menjadi modus.)"),
    ("content/statistika/latihan.ts", "Ia berarti perlu diperiksa dari mana asalnya.", "Artinya, perlu diperiksa dari mana asalnya."),
    ("content/statistika/tahap-hubungan.ts", "Itu saja. Ia tidak membuktikan bahwa", "Itu saja. Diagram pencar tidak membuktikan bahwa"),
    ("content/statistika/tahap-hubungan.ts", "Tanda topi di atas y itu penting. Ia menandakan", "Tanda topi di atas y itu penting. Topi itu menandakan"),
    ("content/statistika/tahap-hubungan.ts", "Ia punya arti: setiap tambahan", "Angka itu punya arti: setiap tambahan"),
    ("content/statistika/tahap-hubungan.ts", "Ia cuma garis, dan ia akan terus naik selamanya", "Garis regresi cuma garis, dan garis itu akan terus naik selamanya"),
    ("content/statistika/tahap-hubungan.ts", "Ia butuh percobaan yang dirancang,", "Sebab-akibat butuh percobaan yang dirancang,"),
    ("content/statistika/tahap-hubungan.ts", "bergerak bersama; ia tidak bisa memberi tahu kenapa.", "bergerak bersama; statistika tidak bisa memberi tahu kenapa."),
    ("content/statistika/tahap-hubungan.ts", "judul: 'Grafik yang menyesatkan'", "judul: 'Grafik yang memberi kesan keliru'"),
    ("content/statistika/tahap-hubungan.ts", "Grafik bisa menyesatkan tanpa satu pun angka yang salah.", "Grafik bisa memberi kesan keliru tanpa satu pun angka yang salah."),
    ("content/statistika/tahap-hubungan.ts", "juga bisa menyesatkan.", "juga bisa memberi kesan keliru."),
    ("content/statistika/tahap-hubungan.ts", "Grafik yang menyesatkan biasanya tidak berisi angka palsu.", "Grafik yang memberi kesan keliru biasanya tidak berisi angka palsu."),
    ("content/statistika/tahap-hubungan.ts", "biasanya bukan kebetulan.", "biasanya disengaja."),
    ("content/statistika/tahap-hubungan.ts", "Ia cuma menuntut kebiasaan untuk berhenti sebentar", "Materi ini cuma menuntut kebiasaan untuk berhenti sebentar"),
    ("content/statistika/tahap-hubungan.ts", "judul: 'Grafik yang datanya benar tidak mungkin menipu'", "judul: 'Dikira grafik yang datanya benar pasti memberi kesan yang benar'"),
    ("content/statistika/tahap-hubungan.ts", "Malah grafik yang paling menyesatkan hampir selalu berisi data yang benar. Yang menyesatkan bukan angkanya,", "Malah grafik yang kesannya paling keliru hampir selalu berisi data yang benar. Yang membuat kesannya keliru bukan angkanya,"),
    ("content/statistika/tahap-nyata.ts", "Ia memperlihatkan enam tempat di luar kelas", "Materi ini memperlihatkan enam tempat di luar kelas"),
    ("content/statistika/tahap-nyata.ts", "Histogramnya bercerita lain:", "Histogramnya menunjukkan hal lain:"),
    ("content/statistika/tahap-nyata.ts", "bukan cuma rumus: ia mengukur", "bukan cuma rumus: simpangan baku mengukur"),
    ("content/statistika/tahap-nyata.ts", "grafik dengan data benar tetap bisa menyesatkan.", "grafik dengan data benar tetap bisa memberi kesan keliru."),
    ("content/statistika/tahap-nyata.ts", "tetap bisa dibuat menyesatkan.", "tetap bisa dibuat memberi kesan keliru."),
    ("content/statistika/tahap-pemusatan.ts", "Mean, dan kenapa ia disebut titik seimbang", "Mean, dan kenapa mean disebut titik seimbang"),
    ("content/statistika/tahap-pemusatan.ts", "Ini bukan kebetulan pada contoh ini saja.", "Ini berlaku bukan pada contoh ini saja."),
    ("content/statistika/tahap-pemusatan.ts", "Ia sekaligus menjelaskan kenapa simpangan baku", "Sifat ini sekaligus menjelaskan kenapa simpangan baku"),
    ("content/statistika/tahap-pemusatan.ts", "Perhatikan garis median di bawah papan. Apakah ia ikut bergeser?", "Perhatikan garis median di bawah papan. Apakah garis itu ikut bergeser?"),
    ("content/statistika/tahap-pemusatan.ts", "karena ia memakai semua data.", "karena mean memakai semua data."),
    ("content/statistika/tahap-pemusatan.ts", "jadi ia menyeret hasilnya.", "jadi data itu menyeret hasilnya."),
    ("content/statistika/tahap-pemusatan.ts", "Menghapus data karena ia mengganggu adalah", "Menghapus data karena mengganggu adalah"),
    ("content/statistika/tahap-pemusatan.ts", "Kalau ternyata memang nyata, ia tetap tinggal,", "Kalau ternyata memang nyata, data itu tetap tinggal,"),
    ("content/statistika/tahap-pemusatan.ts", "JAK kebal terhadap pencilan, sedangkan jangkauan biasa langsung ikut tertipu olehnya.", "JAK kebal terhadap pencilan, sedangkan jangkauan biasa langsung ikut terpengaruh olehnya."),
    ("content/statistika/tahap-pemusatan.ts", "Median sudah kita kenal: ia membelah data", "Median sudah kita kenal: median membelah data"),
    ("content/statistika/tahap-pemusatan.ts", "Ia mengukur lebar setengah data yang di tengah, jadi ia sama sekali tidak peduli", "JAK mengukur lebar setengah data yang di tengah, jadi JAK sama sekali tidak peduli"),
    ("content/statistika/tahap-pemusatan.ts", "Ia belum tentu salah, mungkin memang ada siswa", "Nilai itu belum tentu salah, mungkin memang ada siswa"),
    ("content/statistika/tahap-pemusatan.ts", "Godaannya datang dari histogram.", "Kesan itu datang dari histogram."),
    ("content/statistika/tahap-pemusatan.ts", "Bukan kebetulan: seperti di Materi 05,", "Memang selalu begitu: seperti di Materi 05,"),
    ("content/statistika/tahap-pemusatan.ts", "Angka ini disebut varian. Ia sudah berhasil membedakan", "Angka ini disebut varian. Varian sudah berhasil membedakan"),
    ("content/statistika/tahap-pemusatan.ts", "Ia cuma mengukur lebar sebaran.", "Simpangan baku cuma mengukur lebar sebaran."),
    ("content/statistika/tahap-penyajian.ts", "judul: 'Kenapa satu angka bisa menipu'", "judul: 'Kenapa satu angka bisa memberi kesan keliru'"),
    ("content/statistika/tahap-penyajian.ts", "tetapi ia cuma melihat dua data,", "tetapi jangkauan cuma melihat dua data,"),
    ("content/statistika/tahap-penyajian.ts", "sela itu bukan hiasan: ia menandakan", "sela itu ada artinya: sela itu menandakan"),
    ("content/statistika/tahap-penyajian.ts", "Ia gagal untuk hal lain,", "Diagram lingkaran gagal untuk hal lain,"),
    ("content/statistika/tahap-penyajian.ts", "dan itu bukan hiasan tetapi syarat", "dan itu syarat"),
    ("content/statistika/tahap-penyajian.ts", "judul: 'Lebar kelas mengubah cerita'", "judul: 'Lebar kelas mengubah kesan'"),
    ("content/statistika/tahap-penyajian.ts", "tiap kali hasilnya bisa bercerita lain.", "tiap kali hasilnya bisa memberi kesan lain."),
    ("content/statistika/tahap-penyajian.ts", "membaca tinggi langsung menyesatkan.", "membaca tinggi langsung keliru."),
    ("content/statistika/tahap-penyajian.ts", "Perlakukan ia sebagai saran awal,", "Perlakukan hasilnya sebagai saran awal,"),
    ("content/statistika/tahap-penyajian.ts", "berbeda ukuran hampir selalu menyesatkan.", "berbeda ukuran hampir selalu keliru."),
    ("content/statistika/tahap-penyajian.ts", "Perhatikan kesimpulan di bawah gambar. Apakah ia ikut berubah?", "Perhatikan kesimpulan di bawah gambar. Apakah kesimpulannya ikut berubah?"),
    # ---------------- transformasi-geometri ----------------
    ("content/transformasi-geometri/istilah.ts", "translasi TIDAK punya matriks pengali, ia penjumlahan matriks kolom", "translasi TIDAK punya matriks pengali, translasi adalah penjumlahan matriks kolom"),
    ("content/transformasi-geometri/kuis.ts", "(ia menambah, bukan mengalikan)", "(translasi menambah, bukan mengalikan)"),
    ("content/transformasi-geometri/latihan.ts", "tetapi ia menyatakan seberapa jauh titiknya berpindah", "tetapi selisih itu menyatakan seberapa jauh titiknya berpindah"),
    ("content/transformasi-geometri/tahap.ts", "Ia berarti hasil pemetaan,", "Peta berarti hasil pemetaan,"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: angka 5 memang muncul", "Yang terasa benar: angka 5 memang muncul"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: tanda minus di rumus garisnya", "Yang terasa benar: tanda minus di rumus garisnya"),
    ("content/transformasi-geometri/tahap.ts", "dan itu bukan kebetulan: keduanya berasal dari gagasan jarak sama.", "dan memang begitu: keduanya berasal dari gagasan jarak sama."),
    ("content/transformasi-geometri/tahap.ts", "Itu bukan kebetulan.'", "Itu memang selalu begitu.'"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: keduanya memakai kata \"cermin\".", "Yang terasa benar: keduanya memakai kata \"cermin\"."),
    ("content/transformasi-geometri/tahap.ts", "judul: 'Kesejajaran itu bukan kebetulan'", "judul: 'Kesejajaran itu memang selalu terjadi'"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda di sini adalah angka 2", "Yang terasa benar di sini adalah angka 2"),
    ("content/transformasi-geometri/tahap.ts", "di mana ia sekarang?", "di mana ujungnya sekarang?"),
    ("content/transformasi-geometri/tahap.ts", "ia berpindah dari sumbu X positif ke sumbu Y positif.", "ujungnya berpindah dari sumbu X positif ke sumbu Y positif."),
    ("content/transformasi-geometri/tahap.ts", "Ia setengah putaran, dan kita boleh menyebutnya", "Pencerminan pada titik adalah setengah putaran, dan kita boleh menyebutnya"),
    ("content/transformasi-geometri/tahap.ts", "Ia berada seperempat putaran di depan (1, 0),", "Titik (0, 1) berada seperempat putaran di depan (1, 0),"),
    ("content/transformasi-geometri/tahap.ts", "Jadi ia mendarat di (-sin a, cos a).", "Jadi titik itu mendarat di (-sin a, cos a)."),
    ("content/transformasi-geometri/tahap.ts", "Sekali dikuasai, ia berlaku untuk semua transformasi", "Sekali dikuasai, cara ini berlaku untuk semua transformasi"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: hasilnya (-y, x) memang mengandung pertukaran,", "Yang terasa benar: hasilnya (-y, x) memang mengandung pertukaran,"),
    ("content/transformasi-geometri/tahap.ts", "dan di mana ia muncul kembali sesudahnya?", "dan di mana bentuknya muncul kembali sesudahnya?"),
    ("content/transformasi-geometri/tahap.ts", "Karena itu ia sering disebut terpisah", "Karena itu dilatasi sering disebut terpisah"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: untuk pusat di titik asal,", "Yang terasa benar: untuk pusat di titik asal,"),
    ("content/transformasi-geometri/tahap.ts", "itu sebabnya ia tidak masuk keluarga yang empat.", "itu sebabnya dilatasi tidak masuk keluarga yang empat."),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: empat transformasi lain memang mempertahankan jarak,", "Yang terasa benar: empat transformasi lain memang mempertahankan jarak,"),
    ("content/transformasi-geometri/tahap.ts", "Ia cuma cara lain menuliskan rotasi 90 derajat", "Matriks itu cuma cara lain menuliskan rotasi 90 derajat"),
    ("content/transformasi-geometri/tahap.ts", "dan ia tidak akan keluar di soal.", "dan determinan tidak akan keluar di soal."),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: koordinat (x, y) dan baris matriks", "Yang terasa benar: koordinat (x, y) dan baris matriks"),
    ("content/transformasi-geometri/tahap.ts", "jadi ia tetap di (1, 0)", "jadi titiknya tetap di (1, 0)"),
    ("content/transformasi-geometri/tahap.ts", "Ia ditulis sebagai PENJUMLAHAN matriks kolom.", "Translasi ditulis sebagai PENJUMLAHAN matriks kolom."),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: empat transformasi lain memang begitu,", "Yang terasa benar: empat transformasi lain memang begitu,"),
    ("content/transformasi-geometri/tahap.ts", "karena ia yang paling dekat dengan bilangannya.", "karena posisinya paling dekat dengan bilangannya."),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: langkah pertama sudah memberi jawaban", "Yang terasa benar: langkah pertama sudah memberi jawaban"),
    ("content/transformasi-geometri/tahap.ts", "Yang menggoda: begitulah cara kita membaca kalimat,", "Yang terasa benar: begitulah cara kita membaca kalimat,"),
    ("content/transformasi-geometri/tahap.ts", "karena ia yang paling dekat dengan titiknya.", "karena posisinya paling dekat dengan titiknya."),
    ("content/transformasi-geometri/tahap.ts", "tidak bisa digabungkan lewat perkalian, karena ia penjumlahan.", "tidak bisa digabungkan lewat perkalian, karena translasi adalah penjumlahan."),
    # ---------------- trigonometri ----------------
    ("content/trigonometri/istilah.ts", "karena ia ruas pada garis singgung", "karena tangen adalah ruas pada garis singgung"),
    ("content/trigonometri/kuis.ts", " * kenapa pengecoh menggoda.", " * kenapa pengecoh tampak benar."),
    ("content/trigonometri/kuis.ts", "sehingga ia separuh dari segitiga sama sisi", "sehingga segitiga itu separuh dari segitiga sama sisi"),
    ("content/trigonometri/latihan.ts", "Dan malah karena ia perbandingan,", "Dan malah karena nilainya perbandingan,"),
    ("content/trigonometri/latihan.ts", "walaupun ia tidak pernah tahu", "walaupun kalkulator tidak pernah tahu"),
    ("content/trigonometri/tahap.ts", "Padahal ia lahir dari kebutuhan yang sangat praktis", "Padahal trigonometri lahir dari kebutuhan yang sangat praktis"),
    ("content/trigonometri/tahap.ts", "dan ia memang tidak perlu tahu segitiga mana", "dan kalkulator memang tidak perlu tahu segitiga mana"),
    ("content/trigonometri/tahap.ts", "hafalan itu langsung menyesatkan.", "hafalan itu langsung salah."),
    ("content/trigonometri/tahap.ts", "Anda akan melihat ia benar-benar berupa garis", "Anda akan melihat tangen benar-benar berupa ruas garis"),
    ("content/trigonometri/tahap.ts", "ke arah mana pun ia menunjuk.", "ke arah mana pun jari-jarinya menunjuk."),
    ("content/trigonometri/tahap.ts", "Ia bukan hiasan, ia mengubah tiga pecahan jadi satu titik", "Lingkaran satuan bukan gambar tambahan; lingkaran itu mengubah tiga pecahan jadi satu titik"),
    ("content/trigonometri/tahap.ts", "Padahal ia segitiga yang sama,", "Padahal lingkaran satuan memakai segitiga yang sama,"),
    ("content/trigonometri/tahap.ts", "Ia memang ruas pada garis singgung.", "Tangen memang ruas pada garis singgung."),
    ("content/trigonometri/tahap.ts", "Pernahkah ia lebih pendek daripada jari-jari?", "Pernahkah ruas itu lebih pendek daripada jari-jari?"),
    ("content/trigonometri/tahap.ts", "Jadi sin 30° = 1/2 - tepat setengah, bukan kebetulan", "Jadi sin 30° = 1/2 - tepat setengah, dan memang harus begitu"),
    ("content/trigonometri/tahap.ts", "Gelombang bukan bentuk baru - ia rekaman tinggi sebuah putaran.", "Gelombang bukan bentuk baru - gelombang itu rekaman tinggi sebuah putaran."),
    ("content/trigonometri/tahap.ts", "Sekarang biarkan ia terus berputar,", "Sekarang biarkan titiknya terus berputar,"),
    ("content/trigonometri/tahap.ts", "dan di mana ia paling rendah?", "dan di mana kurva paling rendah?"),
    ("content/trigonometri/tahap.ts", "ia grafik nilai terhadap sudut,", "kurva ini grafik nilai terhadap sudut,"),
    ("content/trigonometri/tahap.ts", "pada kemiringan berapa ia memutuskan berbalik.", "pada kemiringan berapa layarnya berbalik."),
    ("content/trigonometri/tahap.ts", "punya kembaran di kuadran I, namanya sudut acuan.", "punya pasangan di kuadran I, namanya sudut acuan."),
    ("content/trigonometri/tahap.ts", "judul: 'Dua titik yang bersaudara'", "judul: 'Dua titik yang berpasangan'"),
    # ---------------- turunan ----------------
    ("content/turunan/kuis.ts", "sehingga ia bukan titik singgung.", "sehingga titik itu bukan titik singgung."),
    ("content/turunan/tahap.ts", "Itulah sebabnya ia disebut rata-rata.", "Itulah sebabnya angka itu disebut rata-rata."),
    ("content/turunan/tahap.ts", "Kata rata-rata di sini bukan hiasan.", "Kata rata-rata di sini penting."),
    ("content/turunan/tahap.ts", "Godaannya masuk akal: kalau ditanya rata-rata", "Terasa masuk akal: kalau ditanya rata-rata"),
    ("content/turunan/tahap.ts", "Ia hanya menghitung selisih ujung dibagi selisih waktu,", "Laju rata-rata hanya menghitung selisih ujung dibagi selisih waktu,"),
    ("content/turunan/tahap.ts", "dan kali ini ia punya arti gambar.", "dan kali ini bentuk itu punya arti gambar."),
    ("content/turunan/tahap.ts", "Godaannya wajar: garis itulah yang baru saja lahir", "Terasa wajar: garis itulah yang baru saja lahir"),
    ("content/turunan/tahap.ts", "Ia mengingatkan asal usulnya, yaitu perubahan y dibagi perubahan x", "Cara ini mengingatkan asal usulnya, yaitu perubahan y dibagi perubahan x"),
    ("content/turunan/tahap.ts", "Godaannya kuat pada f(x) = x²,", "Terasa benar pada f(x) = x²,"),
    ("content/turunan/tahap.ts", "Ia hasil hitungan limit yang sama, diulang untuk tiap pangkat.", "Aturan pangkat adalah hasil hitungan limit yang sama, diulang untuk tiap pangkat."),
    ("content/turunan/tahap.ts", "Godaannya besar karena separuh kalimat itu memang benar.", "Terasa benar karena separuh kalimat itu memang benar."),
    ("content/turunan/tahap.ts", "Kemudahan tadi menggoda untuk dipakai di mana-mana. Sayangnya ia hanya berlaku", "Kemudahan tadi membuat orang ingin memakainya di mana-mana. Sayangnya cara itu hanya berlaku"),
    ("content/turunan/tahap.ts", "Godaannya kuat karena polanya terasa seragam.", "Terasa benar karena polanya terasa seragam."),
    ("content/turunan/tahap.ts", "Pojok kecilnya tidak: ia hasil perkalian DUA tambahan yang sama-sama mengecil, jadi ia menyusut", "Pojok kecilnya tidak: pojok itu hasil perkalian DUA tambahan yang sama-sama mengecil, jadi pojok itu menyusut"),
    ("content/turunan/tahap.ts", "Godaannya masuk akal, karena pada perkalian", "Terasa masuk akal, karena pada perkalian"),
    ("content/turunan/tahap.ts", "Ia turunan dari x² + 1, yaitu bagian", "Angka itu turunan dari x² + 1, yaitu bagian"),
    ("content/turunan/tahap.ts", "Godaannya besar karena bagian itu sudah terlihat lengkap", "Terasa benar karena bagian itu sudah terlihat lengkap"),
    ("content/turunan/tahap.ts", "Ia grafik kosinus.", "Kurva itu grafik kosinus."),
    ("content/turunan/tahap.ts", "Sesudah itu ia menurun, jadi kemiringannya negatif.", "Sesudah itu kurvanya menurun, jadi kemiringannya negatif."),
    ("content/turunan/tahap.ts", "Jadi hasil bacaan grafik tadi memang benar, bukan kebetulan.", "Jadi hasil bacaan grafik tadi memang benar."),
    ("content/turunan/tahap.ts", "dan ia bukan bilangan bulat.", "dan bilangan itu bukan bilangan bulat."),
    ("content/turunan/tahap.ts", "Godaannya besar karena setengahnya memang benar.", "Terasa benar karena setengahnya memang benar."),
    ("content/turunan/tahap.ts", "Hasil kedua itu bukan kebetulan dan bukan kasus aneh.", "Hasil kedua itu bukan kasus aneh."),
    ("content/turunan/tahap.ts", "Godaan terbesar setelah menguasai tabel tanda adalah", "Kekeliruan yang paling sering muncul setelah menguasai tabel tanda adalah"),
    ("content/turunan/tahap.ts", "Apakah ia benar-benar berbalik arah", "Apakah kurvanya benar-benar berbalik arah"),
    ("content/turunan/tahap.ts", "Kalau tandanya sama, ia hanya mendatar sesaat.", "Kalau tandanya sama, kurvanya hanya mendatar sesaat."),
    ("content/turunan/tahap.ts", "Godaannya wajar karena angka itulah hasil kerja paling berat.", "Terasa wajar karena angka itulah hasil kerja paling berat."),
    # ---------------- vektor ----------------
    ("content/vektor/kuis.ts", "sehingga ia vektor.", "sehingga perpindahan adalah vektor."),
    ("content/vektor/tahap.ts", "Namun begitu mendarat, ia tidak berada di seberang tempat ia berangkat. Ia berada jauh di hilir.", "Namun begitu mendarat, perahu tidak berada di seberang tempat berangkatnya. Perahu berada jauh di hilir."),
    ("content/vektor/tahap.ts", "dan malah menyesatkan kalau dipaksa begitu.", "dan malah salah kalau dipaksa begitu."),
    ("content/vektor/tahap.ts", "dan ia satu-satunya vektor yang tidak punya arah.", "dan vektor nol satu-satunya vektor yang tidak punya arah."),
    ("content/vektor/tahap.ts", "panjang vektor satuan. Pernahkah ia berubah?", "panjang vektor satuan. Pernahkah angkanya berubah?"),
    ("content/vektor/tahap.ts", "ke arah mana pun ia menghadap. Vektor (0,6  0,8) panjangnya 1, jadi ia vektor satuan, walaupun ia bukan i maupun j.", "ke arah mana pun vektor itu menghadap. Vektor (0,6  0,8) panjangnya 1, jadi termasuk vektor satuan, walaupun bukan i maupun j."),
    ("content/vektor/tahap.ts", "jadi ia menyatakan arah saja.", "jadi vektor satuan menyatakan arah saja."),
    ("content/vektor/tahap.ts", "Dari mana ia berangkat, dan di mana ia berakhir?", "Dari mana panah itu berangkat, dan di mana berakhirnya?"),
    ("content/vektor/tahap.ts", "apa yang ia wakili dalam cerita perjalanan?", "apa yang diwakilinya dalam cerita perjalanan?"),
    ("content/vektor/tahap.ts", "Ia cuma penjumlahan yang salah satu vektornya dibalik arahnya.", "Pengurangan cuma penjumlahan yang salah satu vektornya dibalik arahnya."),
    ("content/vektor/tahap.ts", "arah panah dan panjangnya bercerita.", "arah panah dan panjangnya langsung terbaca."),
    ("content/vektor/tahap.ts", "judul: 'Tandanya bercerita tentang sudutnya'", "judul: 'Tandanya menunjukkan sudutnya'"),
    ("content/vektor/tahap.ts", "jadi ia bukan vektor.", "jadi hasilnya bukan vektor."),
    # ---------------- antarmuka ----------------
    ("components/topik/Kuis.tsx", "'Semua benar. Konsep bab ini sudah pegang.'", "'Semua benar. Bab ini sudah kamu kuasai.'"),
    ("components/topik/Kuis.tsx", "'Sudah kuat. Baca pembahasan soal yang salah di bawah, lalu buka materinya sekali lagi.'", "'Sudah bagus. Baca pembahasan soal yang salah di bawah, lalu buka materinya sekali lagi.'"),
    ("components/topik/Kuis.tsx", "'Separuh jalan. Tiap soal yang salah di bawah menunjuk materi yang perlu dibaca ulang.'", "'Setengahnya benar. Tiap soal yang salah di bawah menunjuk materi yang perlu dibaca ulang.'"),
    ("components/topik/Kuis.tsx", "'Belum nyantol. Baca pembahasannya, buka materi yang ditunjuk, lalu ulangi kuisnya.'", "'Masih banyak yang salah. Baca pembahasannya, buka materi yang ditunjuk, lalu ulangi kuisnya.'"),
    ("components/topik/PanggungRuang3D.tsx", "Itu bukan kebetulan, dan itulah sebabnya jarak selalu diukur tegak lurus.", "Itu memang selalu begitu, dan itulah sebabnya jarak selalu diukur tegak lurus."),
    ("components/topik/PanggungRuang3D.tsx", "Itu simetri kubus, bukan kebetulan.", "Itu simetri kubus."),
    ("components/topik/PanggungVektor.tsx", "Itu bukan kebetulan: membagi sebuah vektor", "Itu memang harus begitu: membagi sebuah vektor"),
]


def main() -> int:
    coba = "--coba" in sys.argv
    gagal = 0
    per_berkas: dict[str, str] = {}
    for rel, lama, baru in GANTI:
        jalur = WEB / rel
        isi = per_berkas.get(rel)
        if isi is None:
            isi = jalur.read_text(encoding="utf-8")
        n = isi.count(lama)
        if n == 0:
            gagal += 1
            print(f"TIDAK ADA  {rel}: {lama[:90]}")
            continue
        per_berkas[rel] = isi.replace(lama, baru)
    if gagal:
        print(f"\n{gagal} teks lama tidak ditemukan; tidak ada yang ditulis")
        return 1
    if coba:
        print(f"semua {len(GANTI)} teks lama ditemukan")
        return 0
    for rel, isi in per_berkas.items():
        (WEB / rel).write_text(isi, encoding="utf-8", newline="\n")
    print(f"{len(GANTI)} penggantian di {len(per_berkas)} berkas")
    return 0


if __name__ == "__main__":
    sys.exit(main())
