/** Istilah bab Trigonometri dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'trigonometri', arti: 'ilmu yang menukar sudut menjadi panjang: yang mudah diukur (sudut, jarak di tanah) ditukar dengan yang tidak bisa dijangkau' },
  { istilah: 'perbandingan trigonometri', arti: 'hasil bagi dua sisi segitiga siku-siku; nilainya hanya bergantung pada sudutnya, bukan pada ukuran segitiganya' },
  { istilah: 'segitiga sebangun', arti: 'dua segitiga dengan bentuk sama dan ukuran berbeda; semua sudutnya sama, sisinya sebanding' },
  { istilah: 'sisi miring', arti: 'sisi terpanjang segitiga siku-siku, menghadap sudut siku-siku; namanya tetap dari sudut mana pun' },
  { istilah: 'sisi depan', arti: 'sisi di seberang sudut yang sedang dilihat; berganti kalau sudutnya berganti' },
  { istilah: 'sisi samping', arti: 'sisi yang menempel pada sudut yang sedang dilihat, selain sisi miring' },
  { istilah: 'sinus (sin)', arti: 'sisi depan dibagi sisi miring; pada lingkaran satuan, tinggi titiknya (koordinat tegak)' },
  { istilah: 'kosinus (cos)', arti: 'sisi samping dibagi sisi miring; pada lingkaran satuan, koordinat mendatar titiknya' },
  { istilah: 'tangen (tan)', arti: 'sisi depan dibagi sisi samping; sama dengan sin dibagi cos; namanya berarti "yang menyentuh" karena ia ruas pada garis singgung' },
  { istilah: 'kotangen (cot)', arti: 'kebalikan tan: sisi samping dibagi sisi depan' },
  { istilah: 'sekan (sec)', arti: 'kebalikan cos: sisi miring dibagi sisi samping (bukan kebalikan sin)' },
  { istilah: 'kosekan (csc)', arti: 'kebalikan sin: sisi miring dibagi sisi depan' },
  { istilah: 'enam rasio', arti: 'enam pembagian dari tiga sisi: sin, cos, tan, cot, sec, csc; semuanya ruas garis sungguhan pada lingkaran satuan' },
  { istilah: 'lingkaran satuan', arti: 'lingkaran berjari-jari 1 berpusat di titik asal; membagi dengan 1 tidak mengubah apa pun, jadi rumus berubah menjadi posisi titik' },
  { istilah: 'sudut istimewa', arti: '30°, 45°, dan 60°: sudut yang nilai trigonometrinya bisa dihitung persis (eksak) tanpa kalkulator, lahir dari persegi dan segitiga sama sisi' },
  { istilah: 'nilai eksak', arti: 'nilai persis berupa pecahan dan akar, seperti √3/2, bukan desimal tak berujung' },
  { istilah: 'kuadran', arti: 'empat daerah bidang koordinat yang dibagi sumbu x dan sumbu y; menentukan tanda sin, cos, tan' },
  { istilah: 'sudut berelasi', arti: 'sudut di kuadran lain yang nilai trigonometrinya sama atau berlawanan tanda dengan sudut lancip acuannya' },
  { istilah: 'grafik sinus', arti: 'catatan tinggi sebuah titik yang berputar pada lingkaran satuan, digambar terhadap sudutnya; bentuknya gelombang' },
  { istilah: 'grafik kosinus', arti: 'grafik sinus yang berangkat 90° lebih awal; mencatat posisi mendatar titik yang berputar' },
  { istilah: 'grafik tangen', arti: 'grafik yang punya jurang setiap 90° karena penyebutnya (cos) menjadi nol' },
  { istilah: 'jurang grafik', arti: 'tempat grafik tan (atau cot, sec, csc) tidak punya nilai; muncul di tempat penyebutnya nol, bukan "nilainya tak hingga"' },
  { istilah: 'periode', arti: 'panjang satu putaran penuh sebelum grafiknya berulang: 360° untuk sin dan cos, 180° untuk tan' },
  { istilah: 'radian', arti: 'ukuran sudut berdasarkan panjang busur pada lingkaran satuan; satu putaran = 2π radian' },
  { istilah: 'sudut elevasi', arti: 'sudut dari garis mendatar ke atas menuju benda yang dilihat' },
  { istilah: 'sudut depresi', arti: 'sudut dari garis mendatar ke bawah menuju benda yang dilihat' },
]
