/** Istilah bab Integral dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'antiturunan', arti: 'fungsi yang turunannya adalah fungsi yang diberikan; jalan dari laju kembali ke jumlah' },
  { istilah: 'tetapan C', arti: 'tambahan pada setiap antiturunan: laju hanya memberi tahu bentuk kurva, bukan letaknya; C dikunci oleh satu keterangan tambahan' },
  { istilah: 'integral tak tentu', arti: '∫ f(x) dx, "semua antiturunan f terhadap x"; hasilnya keluarga fungsi + C' },
  { istilah: 'integran', arti: 'fungsi yang berada di antara tanda ∫ dan dx' },
  { istilah: 'dx', arti: 'penanda bahwa peubah integrasinya x' },
  { istilah: 'aturan pangkat integral', arti: '∫ xⁿ dx = xⁿ⁺¹/(n + 1) + C: naikkan pangkatnya satu, bagi dengan pangkat yang baru; berlaku untuk semua pangkat kecuali −1' },
  { istilah: 'memeriksa dengan menurunkan', arti: 'setiap hasil integral bisa diperiksa sendiri: turunkan hasilnya, harus kembali ke integrannya' },
  { istilah: 'substitusi', arti: 'aturan rantai yang dibaca dari kanan ke kiri: namai lapisan dalam u, hitung du, bentuk soal harus memuat du itu' },
  { istilah: 'lapisan dalam', arti: 'bagian di dalam kurung atau di dalam fungsi, misalnya 2x + 1 pada (2x + 1)⁵; calon u' },
  { istilah: 'integral parsial', arti: 'aturan hasil kali yang dibaca dari arah sebaliknya: ∫ u dv = uv − ∫ v du; pilih u yang menjadi sederhana kalau diturunkan' },
  { istilah: 'antiturunan sinus dan kosinus', arti: '∫ sin x dx = −cos x + C (tanda minus milik sinus); ∫ cos x dx = sin x + C' },
  { istilah: 'antiturunan eksponen', arti: '∫ eˣ dx = eˣ + C' },
  { istilah: 'jumlahan Riemann', arti: 'menutupi daerah bertepi lengkung dengan persegi panjang yang luasnya bisa dihitung, lalu menjumlahkannya' },
  { istilah: 'titik sampel', arti: 'titik di tiap bagian selang yang tingginya dipakai untuk persegi panjang: kiri, kanan, atau tengah' },
  { istilah: 'jepitan', arti: 'jumlahan kiri dan kanan mengapit luas sebenarnya; makin banyak persegi panjangnya, makin rapat jepitannya' },
  { istilah: 'integral tentu', arti: '∫ₐᵇ f(x) dx, nilai yang dituju jumlahan Riemann saat banyak bagiannya diperbesar tanpa henti; hasilnya sebuah bilangan' },
  { istilah: 'batas bawah dan batas atas', arti: 'angka a dan b pada tanda integral: selang yang dihitung dari a sampai b' },
  { istilah: 'luas bertanda', arti: 'yang dihitung integral tentu: bagian di bawah sumbu x masuk dengan tanda negatif' },
  { istilah: 'sifat integral tentu', arti: 'selang boleh dipecah di titik mana pun, batas boleh dibalik dengan mengganti tanda, kelipatan boleh dikeluarkan' },
  { istilah: 'fungsi luas A(x)', arti: 'luas bertanda dari a sampai x; berubah saat x digeser' },
  { istilah: 'Teorema Dasar Kalkulus I', arti: 'laju bertambahnya luas di titik x sama dengan tinggi kurva di titik itu; fungsi luas adalah antiturunan' },
  { istilah: 'Teorema Dasar Kalkulus II', arti: '∫ₐᵇ f(x) dx = F(b) − F(a) dengan F antiturunan f; C hilang dengan sendirinya' },
  { istilah: 'tanda kurung siku', arti: '[F(x)]ₐᵇ, cara menyimpan antiturunan sebelum batasnya dimasukkan: batas atas dikurangi batas bawah' },
  { istilah: 'mengganti batas', arti: 'saat substitusi pada integral tentu, batas x diganti ke batas u, atau hasilnya dikembalikan dulu ke x; jangan dicampur' },
  { istilah: 'luas daerah', arti: 'luas yang terlihat, selalu positif: pecah selang di titik potong sumbu, positifkan tiap bagian, baru jumlahkan' },
  { istilah: 'luas antara dua kurva', arti: 'integral dari (kurva atas − kurva bawah) dengan batas dari titik potong kedua kurva; kalau bertukar posisi, pecah di titik tukar' },
  { istilah: 'dari laju ke jumlah', arti: 'pola bab ini: yang diketahui lajunya, yang dicari jumlahnya = luas di bawah grafik laju; satuannya satuan y dikali satuan x' },
]
