/** Istilah bab Vektor dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'vektor', arti: 'besaran yang butuh besar DAN arah; digambar sebagai ruas garis berarah (panah)' },
  { istilah: 'skalar', arti: 'besaran yang cukup satu angka, seperti massa, suhu, dan waktu' },
  { istilah: 'ruas garis berarah', arti: 'panah: lurus, berkepala di satu ujung; yang menentukan hanya panjang dan arahnya, bukan letaknya' },
  { istilah: 'pangkal dan ujung', arti: 'titik awal panah (pangkal) dan titik berkepala panah (ujung)' },
  { istilah: 'vektor lawan', arti: 'vektor yang sama panjang tetapi berlawanan arah, ditulis −a' },
  { istilah: 'komponen', arti: 'dua angka yang mewakili satu panah: langkah mendatar dan langkah tegak; urutannya tidak boleh ditukar' },
  { istilah: 'vektor baris', arti: 'penulisan komponen mendatar tanpa koma, misalnya (3 4), supaya tidak tertukar dengan titik koordinat' },
  { istilah: 'vektor kolom', arti: 'penulisan komponen bertumpuk ke bawah' },
  { istilah: 'vektor posisi', arti: 'vektor yang pangkalnya di titik asal O; komponennya sama dengan koordinat ujungnya' },
  { istilah: 'vektor AB', arti: 'vektor dari A ke B, dihitung ujung dikurangi pangkal: b − a' },
  { istilah: 'panjang vektor', arti: '|(a b)| = √(a² + b²), Pythagoras; tidak pernah negatif' },
  { istilah: 'arah vektor', arti: 'dinyatakan dalam derajat dari sumbu x, atau dalam mata angin' },
  { istilah: 'vektor satuan', arti: 'vektor yang panjangnya tepat 1; dibuat dengan membagi tiap komponen dengan panjang vektornya; menyatakan arah saja' },
  { istilah: 'i dan j', arti: 'vektor satuan searah sumbu x dan sumbu y: i = (1 0), j = (0 1); (3 4) = 3i + 4j' },
  { istilah: 'resultan', arti: 'hasil penjumlahan vektor' },
  { istilah: 'metode segitiga', arti: 'menjumlah dengan menyambung ujung ke pangkal, lalu menarik panah dari awal ke akhir' },
  { istilah: 'metode poligon', arti: 'metode segitiga untuk lebih dari dua vektor: sambung terus ujung ke pangkal' },
  { istilah: 'metode jajar genjang', arti: 'menjumlah dua vektor yang bekerja serentak dari satu titik; resultannya diagonal jajar genjang dari titik pangkal' },
  { istilah: 'pengurangan vektor', arti: 'a − b = a + (−b): a ditambah lawan b; kalau keduanya dari titik asal, a − b adalah panah dari ujung b ke ujung a' },
  { istilah: 'perkalian skalar', arti: 'vektor dikali bilangan: tiap komponen dikalikan; pengali positif menjaga arah, negatif membalik arah, panjangnya dikali |k|' },
  { istilah: 'sejajar', arti: 'dua vektor yang salah satunya kelipatan yang lain' },
  { istilah: 'perkalian titik', arti: 'a · b, hasilnya angka, bukan vektor: kalikan komponen sejenis lalu jumlahkan, atau |a| |b| cos θ' },
  { istilah: 'tegak lurus', arti: 'dua vektor dengan perkalian titik nol' },
  { istilah: 'proyeksi', arti: 'bayangan satu panah pada panah lain: panjang proyeksi a pada b = (a · b)/|b| (angka), vektor proyeksinya searah b' },
]
