/** Istilah bab Limit dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'limit', arti: 'angka yang dituju f(x) saat x didorong mendekati suatu titik c dari kiri dan kanan, tanpa pernah diletakkan tepat di c' },
  { istilah: 'mendekati', arti: 'dibuat sedekat mungkin tanpa harus sampai; limit tidak peduli apa yang terjadi tepat di titiknya, hanya tetangganya' },
  { istilah: 'limit kiri', arti: 'nilai yang dituju f(x) saat x mendekati c dari sisi yang lebih kecil (kiri)' },
  { istilah: 'limit kanan', arti: 'nilai yang dituju f(x) saat x mendekati c dari sisi yang lebih besar (kanan)' },
  { istilah: 'limit tidak ada', arti: 'limit kiri dan limit kanan berbeda (atau nilainya meledak); bukan nol dan bukan tak hingga, tetapi tidak ada' },
  { istilah: 'nilai fungsi', arti: 'f(c), angka yang dikeluarkan fungsi tepat di titik c; bisa ada tanpa limit, dan limit bisa ada tanpa nilai fungsi' },
  { istilah: 'lubang', arti: 'titik pada grafik yang kosong karena fungsinya tidak punya nilai di situ, padahal tetangganya menuju satu angka' },
  { istilah: 'bentuk 0/0', arti: 'hasil substitusi yang belum memberi tahu apa-apa; tanda bahwa bentuknya harus ditulis ulang (memfaktorkan, sekawan, atau membagi pangkat tertinggi)' },
  { istilah: 'substitusi langsung', arti: 'menghitung limit dengan memasukkan angkanya; jalan pintas yang sah untuk suku banyak dan pecahan yang penyebutnya tidak nol' },
  { istilah: 'sifat limit', arti: 'tujuh aturan yang membolehkan limit dipecah: limit jumlah, selisih, kali, bagi, dan kelipatan' },
  { istilah: 'memfaktorkan', arti: 'menulis pembilang dan penyebut sebagai perkalian supaya faktor yang membuat penyebut nol bisa dicoret' },
  { istilah: 'sekawan', arti: 'bentuk pasangan akar, misalnya √x + 3 untuk √x − 3; dikalikan ke atas dan bawah supaya akarnya lenyap' },
  { istilah: 'pangkat tertinggi', arti: 'pangkat x terbesar dalam pecahan; membagi pembilang dan penyebut dengannya adalah cara menghitung limit di tak hingga' },
  { istilah: 'tak hingga', arti: 'bukan bilangan, tetapi keterangan arah: x dibuat sebesar-besarnya tanpa batas; tidak bisa disubstitusi' },
  { istilah: 'asimtot datar', arti: 'garis mendatar yang didekati grafik saat x lari ke tak hingga, tanpa pernah disentuh' },
  { istilah: 'asimtot tegak', arti: 'garis tegak tempat grafik meledak ke atas atau ke bawah, biasanya di tempat penyebut bernilai nol' },
  { istilah: 'kecepatan sesaat', arti: 'kecepatan pada satu saat, dihitung sebagai limit dari jarak dibagi waktu saat selangnya dibuat mengecil' },
  { istilah: 'limit sin x/x', arti: 'menuju tepat 1 saat x mendekati 0, asalkan sudutnya dalam radian; dibuktikan lewat jepitan di lingkaran satuan' },
  { istilah: 'teorema apit (jepitan)', arti: 'kalau sebuah fungsi terjepit di antara dua fungsi yang menuju angka yang sama, fungsi itu ikut menuju angka itu' },
  { istilah: 'kontinu', arti: 'fungsi yang tidak putus di suatu titik: nilainya ada, limitnya ada, dan keduanya sama' },
  { istilah: 'tiga syarat kontinu', arti: 'f(c) ada, lim x→c f(x) ada, dan keduanya sama; ketiganya wajib' },
  { istilah: 'diskontinu', arti: 'gagal kontinu: berlubang, melompat, meledak, atau nilainya digeser dari limitnya' },
  { istilah: 'suku banyak (polinom)', arti: 'fungsi berbentuk jumlah pangkat x dengan koefisien, misalnya x³ − 2x + 1; kontinu di semua titik' },
]
