/** Istilah bab Grafik Fungsi dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'fungsi', arti: 'mesin aturan: satu masukan menghasilkan tepat satu keluaran' },
  { istilah: 'grafik fungsi', arti: 'kumpulan titik (x, f(x)); jejak mesin itu dijalankan berkali-kali, bukan bentuk yang harus dihafal' },
  { istilah: 'uji garis tegak', arti: 'geser garis tegak menyusuri gambar; kalau ada posisi yang memotong lebih dari sekali, gambar itu bukan grafik fungsi' },
  { istilah: 'domain', arti: 'semua x yang boleh dimasukkan ke fungsi' },
  { istilah: 'range', arti: 'semua y yang mungkin keluar dari fungsi' },
  { istilah: 'parabola', arti: 'grafik fungsi kuadrat, berbentuk lengkung simetris dengan satu puncak' },
  { istilah: 'bentuk puncak', arti: 'y = a(x − h)² + k; puncaknya langsung terbaca di (h, k)' },
  { istilah: 'bentuk umum', arti: 'y = ax² + bx + c; bentuk puncak yang kurungnya sudah dijabarkan' },
  { istilah: 'bentuk faktor', arti: 'y = a(x − p)(x − q); titik potong sumbu x langsung terbaca di p dan q' },
  { istilah: 'puncak', arti: 'titik tertinggi atau terendah parabola, terletak di (h, k) atau di x = −b/2a' },
  { istilah: 'sumbu simetri', arti: 'garis tegak x = h yang membelah parabola jadi dua bagian yang saling mencerminkan' },
  { istilah: 'diskriminan', arti: 'D = b² − 4ac; menentukan berapa kali parabola memotong sumbu x: dua kali (D > 0), sekali (D = 0), tidak sama sekali (D < 0)' },
  { istilah: 'melengkapkan kuadrat', arti: 'cara mengubah bentuk umum kembali ke bentuk puncak' },
  { istilah: 'transformasi grafik', arti: 'enam perlakuan pada rumus (geser, cermin, regang) yang akibatnya pada gambar selalu sama untuk fungsi apa pun' },
  { istilah: 'di luar kurung', arti: 'angka yang ditulis di luar f( ) mengerjakan apa yang tertulis: f(x) + k menggeser ke atas, −f(x) mencerminkan pada sumbu x' },
  { istilah: 'di dalam kurung', arti: 'angka yang masuk ke dalam f( ) mengerjakan kebalikannya: f(x − h) menggeser ke kanan, f(2x) menyempitkan' },
  { istilah: 'nilai mutlak', arti: '|x|, jarak dari nol, tidak pernah negatif; grafiknya bentuk V' },
  { istilah: 'melipat grafik', arti: 'y = |f(x)| melipat bagian di bawah sumbu x ke atas; y = f(|x|) membuang bagian kiri dan menyalin bagian kanan sebagai cermin' },
  { istilah: 'fungsi eksponen', arti: 'y = a · bˣ; mengalikan dengan angka tetap b tiap langkah, bukan menambah' },
  { istilah: 'tumbuh dan meluruh', arti: 'b > 1 berarti tumbuh (makin cepat), 0 < b < 1 berarti meluruh (mengecil terus tanpa pernah nol)' },
  { istilah: 'logaritma', arti: 'pertanyaan "pangkat berapa": ᵇlog c = x berarti bˣ = c; grafiknya cerminan eksponen pada garis y = x' },
  { istilah: 'fungsi rasional', arti: 'pecahan yang pembilang dan penyebutnya berupa fungsi, misalnya 1/(x − 2)' },
  { istilah: 'asimtot tegak', arti: 'garis tegak di tempat penyebut bernilai nol; fungsinya tidak punya nilai di situ' },
  { istilah: 'asimtot datar', arti: 'garis mendatar yang didekati grafik saat x dibuat sangat besar atau sangat kecil, tanpa disentuh' },
  { istilah: 'komposisi fungsi', arti: '(f ∘ g)(x) = f(g(x)): keluaran g dimasukkan ke f; yang bekerja lebih dulu adalah yang paling dekat dengan x' },
  { istilah: 'fungsi invers', arti: 'f⁻¹, mesin yang membatalkan f langkah demi langkah dengan urutan terbalik; bukan 1/f' },
  { istilah: 'fungsi satu-satu', arti: 'fungsi yang tiap keluarannya berasal dari tepat satu masukan; syarat punya invers, diperiksa dengan uji garis mendatar' },
  { istilah: 'uji garis mendatar', arti: 'geser garis mendatar; kalau ada yang memotong grafik lebih dari sekali, fungsinya tidak satu-satu dan tidak punya invers' },
]
