/** Istilah bab Statistika dalam bahasa MANTRA: bekal Asisten Tanya (istilah ini menang atas istilah buku). */
export const ISTILAH: { istilah: string; arti: string }[] = [
  { istilah: 'data kategori', arti: 'data berupa golongan (warna, jurusan); disajikan dengan diagram batang, urutannya boleh ditukar' },
  { istilah: 'data angka', arti: 'data berupa bilangan yang bisa diurutkan dan dikelompokkan; disajikan dengan histogram atau line plot' },
  { istilah: 'diagram batang', arti: 'gambar untuk data kategori: batang renggang, tinggi batang = banyaknya' },
  { istilah: 'histogram', arti: 'gambar untuk data angka yang dikelompokkan: batang rapat, urutan tidak boleh ditukar, dibaca lewat LUAS batang' },
  { istilah: 'line plot (diagram titik)', arti: 'setiap data digambar apa adanya sebagai titik di atas garis bilangan; tidak ada yang disembunyikan' },
  { istilah: 'lebar kelas', arti: 'lebar tiap kelompok pada histogram; pilihan manusia, bukan hasil rumus, dan bisa mengubah bentuk gambarnya' },
  { istilah: 'frekuensi', arti: 'banyaknya data yang jatuh di satu kategori atau kelas' },
  { istilah: 'frekuensi relatif', arti: 'frekuensi dibagi banyak data; menyamakan takaran dua kelompok yang jumlahnya berbeda; jumlah seluruhnya 1 atau 100 persen' },
  { istilah: 'ukuran pemusatan', arti: 'angka yang mewakili "biasanya berapa": mean, median, modus' },
  { istilah: 'ukuran penyebaran', arti: 'angka yang mewakili seberapa jauh data berpencar: jangkauan, JAK, simpangan baku' },
  { istilah: 'mean (rata-rata)', arti: 'jumlah semua data dibagi banyaknya; titik seimbang: jumlah simpangan ke kiri sama dengan ke kanan' },
  { istilah: 'median', arti: 'nilai di tengah setelah data DIURUTKAN; kalau banyak datanya genap, rata-rata dua nilai tengah' },
  { istilah: 'modus', arti: 'nilai yang paling sering muncul; boleh lebih dari satu, boleh tidak ada' },
  { istilah: 'pencilan', arti: 'data yang letaknya jauh terpisah dari kumpulan lainnya; menarik mean, hampir tidak menggeser median; tidak otomatis salah' },
  { istilah: 'kuartil', arti: 'tiga nilai (Q1, Q2 = median, Q3) yang membelah data terurut menjadi empat bagian sama banyak' },
  { istilah: 'ringkasan lima angka', arti: 'minimum, Q1, median, Q3, maksimum' },
  { istilah: 'boxplot', arti: 'gambar ringkasan lima angka: kotak dari Q1 ke Q3 dengan garis median, dan kumis ke minimum dan maksimum' },
  { istilah: 'jangkauan', arti: 'maksimum dikurangi minimum; langsung terpengaruh pencilan' },
  { istilah: 'jangkauan antar kuartil (JAK)', arti: 'Q3 − Q1, lebar setengah data yang di tengah; kebal terhadap pencilan' },
  { istilah: 'simpangan', arti: 'jarak sebuah data ke mean, x − x̄; jumlah semua simpangan selalu nol' },
  { istilah: 'varian', arti: 'rata-rata kuadrat simpangan; satuannya kuadrat satuan data' },
  { istilah: 'simpangan baku', arti: 'akar dari varian; seberapa jauh data biasanya menyimpang dari mean, dalam satuan data aslinya' },
  { istilah: 'data berkelompok', arti: 'data yang hanya diketahui tabel kelasnya; tiap kelas diwakili titik tengahnya, jadi semua hasilnya hampiran' },
  { istilah: 'tepi kelas', arti: 'batas sesungguhnya antara dua kelas berdampingan, misalnya 59,5 antara kelas 50-59 dan 60-69' },
  { istilah: 'interpolasi', arti: 'masuk ke dalam kelas sejauh bagian yang masih kurang; cara mencari median dan kuartil data berkelompok' },
  { istilah: 'data bivariat', arti: 'satu orang atau benda dicatat dua angkanya sekaligus, misalnya jam belajar dan nilai' },
  { istilah: 'diagram pencar', arti: 'tiap pasangan data digambar sebagai satu titik; dibaca arah, bentuk, dan kekuatan hubungannya' },
  { istilah: 'residu', arti: 'jarak tegak dari sebuah titik ke garis regresi; sisa yang tidak tertangkap garis' },
  { istilah: 'garis regresi', arti: 'garis terbaik ŷ = a + bx yang membuat jumlah kuadrat residu paling kecil (metode kuadrat terkecil)' },
  { istilah: 'interpolasi dan ekstrapolasi', arti: 'meramal di dalam rentang data (relatif aman) dan di luar rentang data (berbahaya)' },
  { istilah: 'koefisien korelasi r', arti: 'angka antara −1 dan 1: tandanya arah hubungan, besarnya kekuatan; hanya mengukur hubungan lurus' },
  { istilah: 'koefisien determinasi r²', arti: 'bagian keragaman y yang bisa dijelaskan garis' },
  { istilah: 'korelasi bukan sebab-akibat', arti: 'hubungan sekuat apa pun tidak membuktikan yang satu menyebabkan yang lain' },
]
